In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
#read data
df=pd.read_csv(r"C:\Users\Dell\Downloads\Job_Placement_Data.csv")
df.head()

gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
0      M           67.00    Others           91.00    Others    Commerce   
1      M           79.33   Central           78.33    Others     Science   
2      M           65.00   Central           68.00   Central        Arts   
3      M           56.00   Central           52.00   Central     Science   
4      M           85.80   Central           73.60   Central    Commerce   

   degree_percentage undergrad_degree work_experience  emp_test_percentage  \
0              58.00         Sci&Tech              No                 55.0   
1              77.48         Sci&Tech             Yes                 86.5   
2              64.00        Comm&Mgmt              No                 75.0   
3              52.00         Sci&Tech              No                 66.0   
4              73.30        Comm&Mgmt              No                 96.8   

  specialisation  mba_percent      status  
0         Mkt&HR        58.80      Placed  
1        Mkt&Fin        66.28      Placed  
2        Mkt&Fin        57.80      Placed  
3         Mkt&HR        59.43  Not Placed  
4        Mkt&Fin        55.50      Placed

In [3]:
#print the detailed info about df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               215 non-null    object 
 1   ssc_percentage       215 non-null    float64
 2   ssc_board            215 non-null    object 
 3   hsc_percentage       215 non-null    float64
 4   hsc_board            215 non-null    object 
 5   hsc_subject          215 non-null    object 
 6   degree_percentage    215 non-null    float64
 7   undergrad_degree     215 non-null    object 
 8   work_experience      215 non-null    object 
 9   emp_test_percentage  215 non-null    float64
 10  specialisation       215 non-null    object 
 11  mba_percent          215 non-null    float64
 12  status               215 non-null    object 
dtypes: float64(5), object(8)
memory usage: 22.0+ KB


In [4]:
df["gender"].value_counts()

M    139
F     76
Name: gender, dtype: int64

In [5]:
df["ssc_board"].value_counts()

Central    116
Others      99
Name: ssc_board, dtype: int64

In [6]:
df["hsc_board"].value_counts()

Others     131
Central     84
Name: hsc_board, dtype: int64

In [7]:
df["hsc_subject"].value_counts()

Commerce    113
Science      91
Arts         11
Name: hsc_subject, dtype: int64

In [8]:
df["undergrad_degree"].value_counts()

Comm&Mgmt    145
Sci&Tech      59
Others        11
Name: undergrad_degree, dtype: int64

In [9]:
df["specialisation"].value_counts()

Mkt&Fin    120
Mkt&HR      95
Name: specialisation, dtype: int64

In [10]:
df["status"].value_counts()

Placed        148
Not Placed     67
Name: status, dtype: int64

In [11]:
x=df.iloc[:,:-1]
x

gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
0        M           67.00    Others           91.00    Others    Commerce   
1        M           79.33   Central           78.33    Others     Science   
2        M           65.00   Central           68.00   Central        Arts   
3        M           56.00   Central           52.00   Central     Science   
4        M           85.80   Central           73.60   Central    Commerce   
..     ...             ...       ...             ...       ...         ...   
210      M           80.60    Others           82.00    Others    Commerce   
211      M           58.00    Others           60.00    Others     Science   
212      M           67.00    Others           67.00    Others    Commerce   
213      F           74.00    Others           66.00    Others    Commerce   
214      M           62.00   Central           58.00    Others     Science   

     degree_percentage undergrad_degree work_experience  emp_test_percentage  \
0                58.00         Sci&Tech              No                 55.0   
1                77.48         Sci&Tech             Yes                 86.5   
2                64.00        Comm&Mgmt              No                 75.0   
3                52.00         Sci&Tech              No                 66.0   
4                73.30        Comm&Mgmt              No                 96.8   
..                 ...              ...             ...                  ...   
210              77.60        Comm&Mgmt              No                 91.0   
211              72.00         Sci&Tech              No                 74.0   
212              73.00        Comm&Mgmt             Yes                 59.0   
213              58.00        Comm&Mgmt              No                 70.0   
214              53.00        Comm&Mgmt              No                 89.0   

    specialisation  mba_percent  
0           Mkt&HR        58.80  
1          Mkt&Fin        66.28  
2          Mkt&Fin        57.80  
3           Mkt&HR        59.43  
4          Mkt&Fin        55.50  
..             ...          ...  
210        Mkt&Fin        74.49  
211        Mkt&Fin        53.62  
212        Mkt&Fin        69.72  
213         Mkt&HR        60.23  
214         Mkt&HR        60.22  

[215 rows x 12 columns]

In [12]:
y=df["status"]
y

0          Placed
1          Placed
2          Placed
3      Not Placed
4          Placed
          ...    
210        Placed
211        Placed
212        Placed
213        Placed
214    Not Placed
Name: status, Length: 215, dtype: object

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder



In [14]:
df.columns

Index(['gender', 'ssc_percentage', 'ssc_board', 'hsc_percentage', 'hsc_board',
       'hsc_subject', 'degree_percentage', 'undergrad_degree',
       'work_experience', 'emp_test_percentage', 'specialisation',
       'mba_percent', 'status'],
      dtype='object')

In [15]:
ct=ColumnTransformer([
    ("oencoder",OrdinalEncoder(),["gender",'ssc_board','hsc_board','hsc_subject','undergrad_degree',
                                 'work_experience',"specialisation"
                                 ])],remainder="passthrough")

In [16]:
x=ct.fit_transform(x)
x

array([[ 1.  ,  1.  ,  1.  , ..., 58.  , 55.  , 58.8 ],
       [ 1.  ,  0.  ,  1.  , ..., 77.48, 86.5 , 66.28],
       [ 1.  ,  0.  ,  0.  , ..., 64.  , 75.  , 57.8 ],
       ...,
       [ 1.  ,  1.  ,  1.  , ..., 73.  , 59.  , 69.72],
       [ 0.  ,  1.  ,  1.  , ..., 58.  , 70.  , 60.23],
       [ 1.  ,  0.  ,  1.  , ..., 53.  , 89.  , 60.22]])

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [18]:
#split data into training and testing
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=1)


In [19]:
#building logistic regression

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
lr=LogisticRegression()
lr.fit(xtrain,ytrain)
ypred=lr.predict(xtest)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.86      0.80      0.83        15
           1       0.90      0.93      0.91        28

    accuracy                           0.88        43
   macro avg       0.88      0.86      0.87        43
weighted avg       0.88      0.88      0.88        43



In [23]:
#predicting new observation

In [24]:
inpdata=[["M",65.00,"Central",68.00,"Central","Arts",64.00,"Comm&Mgmt","No",75.0,"Mkt&Fin",57.80]]

In [25]:
df.columns

Index(['gender', 'ssc_percentage', 'ssc_board', 'hsc_percentage', 'hsc_board',
       'hsc_subject', 'degree_percentage', 'undergrad_degree',
       'work_experience', 'emp_test_percentage', 'specialisation',
       'mba_percent', 'status'],
      dtype='object')

In [26]:
newdf=pd.DataFrame(data=inpdata,columns=['gender', 'ssc_percentage', 'ssc_board', 'hsc_percentage', 'hsc_board',
       'hsc_subject', 'degree_percentage', 'undergrad_degree',
       'work_experience', 'emp_test_percentage', 'specialisation',
       'mba_percent'])

In [27]:
newdf

gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
0      M            65.0   Central            68.0   Central        Arts   

   degree_percentage undergrad_degree work_experience  emp_test_percentage  \
0               64.0        Comm&Mgmt              No                 75.0   

  specialisation  mba_percent  
0        Mkt&Fin         57.8

In [28]:
lr.predict(ct.fit_transform(newdf))

array([1])

In [29]:
import pickle

In [30]:
pickle.dump(ct,open("coltransformer.pkl","wb"))
pickle.dump(lr,open("logmodel.pkl","wb"))